# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-26 07:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20171116_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='principal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
