# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-03 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20171103_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='school_classes',
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_class',
            field=models.CharField(choices=[('Pre-Nursery', 'Pre-Nursery'), ('Nursery', 'Nursery'), ('Kindergarten', 'Kindergarten'), ('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X'), ('XI', 'XI'), ('XII', 'XII')], default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.CharField(choices=[('Pre-Nursery', 'Pre-Nursery'), ('Nursery', 'Nursery'), ('Kindergarten', 'Kindergarten'), ('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X'), ('XI', 'XI'), ('XII', 'XII')], max_length=100),
        ),
    ]
