# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-03 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20171103_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='absent',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='present',
            field=models.IntegerField(),
        ),
    ]
