# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-03 07:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_auto_20171103_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='teacher',
        ),
        migrations.AddField(
            model_name='student',
            name='date',
            field=models.DateField(auto_now=True, default=datetime.datetime(2017, 11, 3, 7, 54, 25, 843231, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='mark_attendance',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
