# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-03 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_auto_20171103_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mark_attendance',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Absent', max_length=50),
        ),
    ]
