# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-03 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_auto_20171103_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_email',
        ),
    ]
