# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-03 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_remove_teacher_teacher_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_class',
            field=models.CharField(blank=True, choices=[('Pre-Nursery', 'Pre-Nursery'), ('Nursery', 'Nursery'), ('Kindergarten', 'Kindergarten'), ('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X'), ('XI', 'XI'), ('XII', 'XII')], default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_school',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.School'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_section',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
