# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-04 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_auto_20171104_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='mark_attendance',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Absent', max_length=50),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
