# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-04 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_auto_20171104_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='section',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_class',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_school',
        ),
        migrations.AddField(
            model_name='student',
            name='student_teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='attendance.Teacher'),
            preserve_default=False,
        ),
    ]
