# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-04 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_auto_20171104_1847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
        migrations.AlterField(
            model_name='student',
            name='mark_attendance',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=50),
        ),
    ]
