# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-13 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0023_auto_20171113_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_teacher',
        ),
        migrations.AddField(
            model_name='student',
            name='student_teacher',
            field=models.ManyToManyField(to='attendance.Teacher'),
        ),
    ]
