# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-13 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0026_auto_20171113_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_teacher',
        ),
    ]
