# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-14 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0038_auto_20171114_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=1, max_length=50),
        ),
    ]
